#!/usr/bin/env bash
set -euo pipefail

RULE_FILE="${RULE_FILE:-/etc/udev/rules.d/99-rjscm-tty.rules}"
SYMLINK_PREFIX="${RJSCM_SYMLINK_PREFIX:-ttyRC}"
USB_VENDOR_ID="${RJSCM_USB_VENDOR_ID:-303a}"
USB_MODEL_ID="${RJSCM_USB_MODEL_ID:-1001}"
USB_MODEL="${RJSCM_USB_MODEL:-USB_JTAG_serial_debug_unit}"

action="install"
dry_run=0
ports=()
tmp_rule_file=""

cleanup() {
    if [[ -n "${tmp_rule_file}" ]]; then
        rm -f "${tmp_rule_file}"
    fi
}

trap cleanup EXIT

usage() {
    cat <<EOF
Usage:
  $0 [install] [--port /dev/ttyACM0 --port /dev/ttyACM1] [--dry-run]
  $0 list
  $0 remove

Creates stable udev symlinks such as /dev/${SYMLINK_PREFIX}0 and /dev/${SYMLINK_PREFIX}1.

The generated rules match:
  - Espressif USB VID:PID ${USB_VENDOR_ID}:${USB_MODEL_ID}
  - model ${USB_MODEL}
  - the current physical USB port path

They intentionally do not match the module serial number. If a module is
replaced but plugged into the same Raspberry Pi USB port, the same /dev/${SYMLINK_PREFIX}*
name is reused.

Options:
  --port PATH       Add a specific current module port. Repeat for two modules.
                    Default: all matching /dev/ttyACM* devices, sorted by name.
  --prefix NAME     Symlink prefix. Default: ${SYMLINK_PREFIX}
  --rule-file PATH  udev rule output path. Default: ${RULE_FILE}
  --dry-run         Print the rule instead of installing it.
  -h, --help        Show this help.
EOF
}

fail() {
    echo "error: $*" >&2
    exit 1
}

need_command() {
    command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

run_root() {
    if [[ "${dry_run}" == "1" ]]; then
        return 0
    fi
    if [[ "${EUID}" == "0" ]]; then
        "$@"
    else
        sudo "$@"
    fi
}

prop() {
    local dev="$1"
    local key="$2"
    udevadm info --query=property --name="${dev}" 2>/dev/null |
        awk -F= -v key="${key}" '$1 == key { print substr($0, length(key) + 2); exit }'
}

udev_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "${value}"
}

is_module_port() {
    local dev="$1"
    [[ -e "${dev}" ]] || return 1
    [[ "$(prop "${dev}" ID_BUS)" == "usb" ]] || return 1
    [[ "$(prop "${dev}" ID_VENDOR_ID)" == "${USB_VENDOR_ID}" ]] || return 1
    [[ "$(prop "${dev}" ID_MODEL_ID)" == "${USB_MODEL_ID}" ]] || return 1
    [[ "$(prop "${dev}" ID_MODEL)" == "${USB_MODEL}" ]] || return 1
    [[ "$(prop "${dev}" ID_USB_DRIVER)" == "cdc_acm" ]] || return 1
    [[ "$(prop "${dev}" ID_USB_INTERFACE_NUM)" == "00" ]] || return 1
    [[ -n "$(prop "${dev}" ID_PATH)" ]] || return 1
}

discover_ports() {
    local dev
    for dev in /dev/ttyACM*; do
        [[ -e "${dev}" ]] || continue
        if is_module_port "${dev}"; then
            printf '%s\n' "${dev}"
        fi
    done | sort -V
}

selected_ports() {
    if [[ "${#ports[@]}" -gt 0 ]]; then
        printf '%s\n' "${ports[@]}"
    else
        discover_ports
    fi
}

list_ports() {
    local index=0
    local dev
    while IFS= read -r dev; do
        [[ -n "${dev}" ]] || continue
        printf '%s -> /dev/%s%s\n' "${dev}" "${SYMLINK_PREFIX}" "${index}"
        printf '  ID_PATH=%s\n' "$(prop "${dev}" ID_PATH)"
        printf '  ID_SERIAL_SHORT=%s\n' "$(prop "${dev}" ID_SERIAL_SHORT)"
        index=$((index + 1))
    done < <(selected_ports)
}

group_rule() {
    if getent group dialout >/dev/null 2>&1; then
        printf ', GROUP="dialout"'
    elif getent group uucp >/dev/null 2>&1; then
        printf ', GROUP="uucp"'
    fi
}

generate_rules() {
    local group
    group="$(group_rule)"

    cat <<EOF
# Generated by soccer-communication-module/scripts/setup_rc_udev.sh
# Stable names for RoboCupJunior Soccer Communication Modules.
# Match by Espressif USB identity plus physical USB port path, not module serial.
ACTION!="add|change", GOTO="rjscm_tty_end"
SUBSYSTEM!="tty", GOTO="rjscm_tty_end"
KERNEL!="ttyACM*", GOTO="rjscm_tty_end"

EOF

    local index=0
    local dev
    local id_path
    local seen_paths=" "
    while IFS= read -r dev; do
        [[ -n "${dev}" ]] || continue
        is_module_port "${dev}" || fail "${dev} is not a matching ESP32-C5 USB serial module"
        id_path="$(prop "${dev}" ID_PATH)"
        [[ "${seen_paths}" != *" ${id_path} "* ]] || fail "duplicate ID_PATH detected: ${id_path}"
        seen_paths="${seen_paths}${id_path} "

        printf 'ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", ENV{ID_MODEL}=="%s", ENV{ID_USB_DRIVER}=="cdc_acm", ENV{ID_USB_INTERFACE_NUM}=="00", ENV{ID_PATH}=="%s", SYMLINK+="%s%s", MODE="0660"%s, TAG+="uaccess", ENV{ID_MM_DEVICE_IGNORE}="1"\n' \
            "$(udev_escape "${USB_VENDOR_ID}")" \
            "$(udev_escape "${USB_MODEL_ID}")" \
            "$(udev_escape "${USB_MODEL}")" \
            "$(udev_escape "${id_path}")" \
            "$(udev_escape "${SYMLINK_PREFIX}")" \
            "${index}" \
            "${group}"
        index=$((index + 1))
    done < <(selected_ports)

    [[ "${index}" -gt 0 ]] || fail "no matching modules found; plug them in and run: $0 list"

    cat <<EOF

LABEL="rjscm_tty_end"
EOF
}

install_rules() {
    tmp_rule_file="$(mktemp)"
    generate_rules > "${tmp_rule_file}"

    if [[ "${dry_run}" == "1" ]]; then
        cat "${tmp_rule_file}"
        return 0
    fi

    run_root install -m 0644 "${tmp_rule_file}" "${RULE_FILE}"
    run_root udevadm control --reload-rules
    run_root udevadm trigger --subsystem-match=tty --action=change

    echo "Installed ${RULE_FILE}"
    echo "Reconnect the modules if the /dev/${SYMLINK_PREFIX}* links do not appear immediately."
    ls -l "/dev/${SYMLINK_PREFIX}"* 2>/dev/null || true
}

remove_rules() {
    if [[ "${dry_run}" == "1" ]]; then
        echo "Would remove ${RULE_FILE}"
        return 0
    fi
    run_root rm -f "${RULE_FILE}"
    run_root udevadm control --reload-rules
    run_root udevadm trigger --subsystem-match=tty --action=change
    echo "Removed ${RULE_FILE}"
}

need_command udevadm
need_command awk
need_command getent

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        install|list|remove)
            action="$1"
            ;;
        --port)
            shift
            [[ "$#" -gt 0 ]] || fail "--port requires a path"
            ports+=("$1")
            ;;
        --prefix)
            shift
            [[ "$#" -gt 0 ]] || fail "--prefix requires a name"
            SYMLINK_PREFIX="$1"
            ;;
        --rule-file)
            shift
            [[ "$#" -gt 0 ]] || fail "--rule-file requires a path"
            RULE_FILE="$1"
            ;;
        --dry-run)
            dry_run=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "unknown argument: $1"
            ;;
    esac
    shift
done

case "${action}" in
    install)
        install_rules
        ;;
    list)
        list_ports
        ;;
    remove)
        remove_rules
        ;;
esac
